CREATE TABLE A (N1 int);
INSERT INTO A VALUES(1);
INSERT INTO A VALUES(2);
CREATE TABLE B (N1 int);
INSERT INTO B VALUES(3);
TRUNCATE TABLE B;
INSERT INTO B VALUES(4);

(1) SELECT SUM(N1) FROM A;
(2) SELECT SUM(N1) FROM B;

[해보기]
(1) 과 (2) 의 결과를 예측해보고 쿼리를 입력하세요.

[정답]
(1) 3
(2) 4